---
- name: this playbook installs httpd
  hosts: all
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed

  - name: start apache
    service:
      name: httpd
      state: started
